# Generated by Django 3.2.7 on 2023-03-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230316_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='time_limit',
        ),
    ]
